---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "flaskblog"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "blog"
  namespace: "flaskblog"
  labels:
    app: "blog"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "blog"
  template:
    metadata:
      labels:
        app: "blog"
    spec:
      containers:
      - name: "softa-image-3-1"
        image: "gcr.io/viikko6-projekti/softa-image-3:latest"
        ports:
          - name: http
            containerPort: 80
          - name: health
            containerPort: 81
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "blog-hpa-zppa"
  namespace: "flaskblog"
  labels:
    app: "blog"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "blog"
    apiVersion: "apps/v1"
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80